Repository jenkins-x/jx3-eagle, pull requests merged in 2021-04, with the labels that each got.

#721 chore: import repository https://github.com/rawlingsj/cosign-test2.git
  .jx/gitops/source-config.yaml
  config-root/namespaces/jx/grafana/grafana-deploy.yaml
  config-root/namespaces/jx/lighthouse-config/config-cm.yaml
  config-root/namespaces/jx/lighthouse-config/plugins-cm.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-foghorn-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-keeper-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-tekton-controller-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-webhooks-deploy.yaml
  config-root/namespaces/jx/source-repositories/rawlingsj-cosign-test2.yaml
Labels: env/dev, size/M, updatebot

#740 fix: add jx-charter
  config-root/cluster/resources/jx/jx-charter/jx-charter-jx-charter-jx-clusterrole.yaml
  config-root/cluster/resources/jx/jx-charter/jx-charter-jx-charter-jx-crb.yaml
  config-root/customresourcedefinitions/jx/jx-charter/charts.chart.jenkins.io-crd.yaml
  config-root/namespaces/cert-manager/chart-crds/cert-manager.yaml
  config-root/namespaces/jx-production/chart-crds/acme.yaml
  config-root/namespaces/jx-staging/chart-crds/cosign-test2.yaml
  config-root/namespaces/jx-staging/chart-crds/go-chaos.yaml
  config-root/namespaces/jx/chart-crds/acme.yaml
  config-root/namespaces/jx/chart-crds/chartmuseum.yaml
  config-root/namespaces/jx/chart-crds/external-dns.yaml
  config-root/namespaces/jx/chart-crds/grafana.yaml
  config-root/namespaces/jx/chart-crds/jenkins-x-crds.yaml
  config-root/namespaces/jx/chart-crds/jmc.yaml
  config-root/namespaces/jx/chart-crds/jx-build-controller.yaml
  config-root/namespaces/jx/chart-crds/jx-charter.yaml
  config-root/namespaces/jx/chart-crds/jx-pipelines-visualizer.yaml
  config-root/namespaces/jx/chart-crds/jx-preview.yaml
  config-root/namespaces/jx/chart-crds/jx-slack.yaml
  config-root/namespaces/jx/chart-crds/jx-test.yaml
  config-root/namespaces/jx/chart-crds/jxboot-helmfile-resources.yaml
  config-root/namespaces/jx/chart-crds/lighthouse.yaml
  config-root/namespaces/jx/chart-crds/nexus.yaml
  config-root/namespaces/jx/chart-crds/pusher-wave.yaml
  config-root/namespaces/jx/charts/bots.yaml
  config-root/namespaces/jx/grafana/grafana-deploy.yaml
  config-root/namespaces/jx/jx-charter/jx-charter-jx-charter-deploy.yaml
  config-root/namespaces/jx/jx-charter/jx-charter-sa.yaml
  config-root/namespaces/nginx/chart-crds/ingress-nginx.yaml
  config-root/namespaces/secret-infra/chart-crds/kubernetes-external-secrets.yaml
  config-root/namespaces/tekton-pipelines/chart-crds/tekton-pipeline.yaml
  config-root/namespaces/tf-system/chart-crds/terraform-operator.yaml
  docs/README.md
  docs/releases.yaml
  helmfiles/jx/helmfile.yaml
Labels: approved, size/XL

#749 chore: bump sdm agent
  helmfiles/sdm/helmfile.yaml
Labels: approved, size/XS

#750 fix: upgrade sdm
  config-root/cluster/resources/sdm/sdm-agent-kubernetes/sdm-agent-kubernetes-sdm-clusterrole.yaml
  config-root/namespaces/cert-manager/chart-crds/cert-manager.yaml
  config-root/namespaces/jx-production/chart-crds/acme.yaml
  config-root/namespaces/jx-staging/chart-crds/cosign-test2.yaml
  config-root/namespaces/jx-staging/chart-crds/go-chaos.yaml
  config-root/namespaces/jx/chart-crds/acme.yaml
  config-root/namespaces/jx/chart-crds/bots.yaml
  config-root/namespaces/jx/chart-crds/chartmuseum.yaml
  config-root/namespaces/jx/chart-crds/external-dns.yaml
  config-root/namespaces/jx/chart-crds/grafana.yaml
  config-root/namespaces/jx/chart-crds/jenkins-x-crds.yaml
  config-root/namespaces/jx/chart-crds/jmc.yaml
  config-root/namespaces/jx/chart-crds/jx-build-controller.yaml
  config-root/namespaces/jx/chart-crds/jx-charter.yaml
  config-root/namespaces/jx/chart-crds/jx-pipelines-visualizer.yaml
  config-root/namespaces/jx/chart-crds/jx-preview.yaml
  config-root/namespaces/jx/chart-crds/jx-slack.yaml
  config-root/namespaces/jx/chart-crds/jx-test.yaml
  config-root/namespaces/jx/chart-crds/jxboot-helmfile-resources.yaml
  config-root/namespaces/jx/chart-crds/lighthouse.yaml
  config-root/namespaces/jx/chart-crds/nexus.yaml
  config-root/namespaces/jx/chart-crds/pusher-wave.yaml
  config-root/namespaces/jx/grafana/grafana-deploy.yaml
  config-root/namespaces/nginx/chart-crds/ingress-nginx.yaml
  config-root/namespaces/sdm/chart-crds/sdm-agent-kubernetes.yaml
  config-root/namespaces/sdm/sdm-agent-kubernetes/sdm-agent-kubernetes-deploy.yaml
  config-root/namespaces/sdm/sdm-agent-kubernetes/sdm-agent-kubernetes-sa.yaml
  config-root/namespaces/secret-infra/chart-crds/kubernetes-external-secrets.yaml
  config-root/namespaces/tekton-pipelines/chart-crds/tekton-pipeline.yaml
  config-root/namespaces/tf-system/chart-crds/terraform-operator.yaml
  docs/README.md
  docs/releases.yaml
  helmfiles/sdm/helmfile.yaml
Labels: approved, size/L

#759 chore: upgrade jx-charter
  config-root/namespaces/jx/chart-crds/bots.yaml
  config-root/namespaces/jx/chart-crds/jx-charter.yaml
  config-root/namespaces/jx/grafana/grafana-deploy.yaml
  config-root/namespaces/jx/jx-charter/jx-charter-jx-charter-deploy.yaml
  docs/README.md
  docs/releases.yaml
  helmfiles/jx/helmfile.yaml
Labels: approved, size/S
