Repository jenkins-x/jx3-eagle, pull requests merged in 2021-06, with the labels that each got.

#883 WIP: try enable by default
  versionStream/charts/jx3/lighthouse/values.yaml.gotmpl
Labels: do-not-merge/work-in-progress, size/XS

#945 chore: import repository https://github.com/jenkins-x-charts/nexus
  .jx/gitops/source-config.yaml
  config-root/namespaces/jx/lighthouse-config/config-cm.yaml
  config-root/namespaces/jx/lighthouse-config/plugins-cm.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-foghorn-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-keeper-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-tekton-controller-deploy.yaml
  config-root/namespaces/jx/lighthouse/lighthouse-webhooks-deploy.yaml
  config-root/namespaces/jx/source-repositories/jenkins-x-charts-nexus.yaml
Labels: env/dev, size/M, updatebot

#953 fix: add lighthouse UI
  config-root/cluster/resources/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-clusterrole.yaml
  config-root/cluster/resources/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-crb.yaml
  config-root/namespaces/jx/chart-crds/lighthouse-webui-plugin.yaml
  config-root/namespaces/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-deploy.yaml
  config-root/namespaces/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-ingress.yaml
  config-root/namespaces/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-persistentvolumeclaim.yaml
  config-root/namespaces/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-sa.yaml
  config-root/namespaces/jx/lighthouse-webui-plugin/lighthouse-webui-plugin-svc.yaml
  docs/README.md
  docs/releases.yaml
  helmfiles/jx/helmfile.yaml
Labels: approved, size/L
